version: '3'

services:
  app:
    image: node:22-alpine
    user: node
    container_name: ietsene
    working_dir: /app
    command: npm run dev
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://0.0.0.0:3000 || exit 1"]  
      interval: 5s
      retries: 3
      start_period: 15s
    volumes:
       - ./:/app
